version: '3.7'

services:
    php-httpd:
        image: php:apache
        build:
            context: .
            dockerfile: PHP.Dockerfile
        ports:
            - 8080:80
        volumes:
            - "./src:/var/www/html"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - XDEBUG_MODE=develop,debug

    mariadb:
        image: mariadb:latest
        environment:
            TZ: "Europe/Paris"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: 'mariadb'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'mariadb'

    phpmyadmin:
        image: phpmyadmin:latest
        links:
            - 'mariadb:db'
        ports:
            - 8081:80
